### ISSUE TITLE
不要使用g++完整路径而是使用直接g++

### ISSUE THREAD

**Issue by huolongguo10** [SweetIceLolly/DragControlsIDE#2]
mingw默认路径是c盘根目录

**Comment by SweetIceLolly** [comment]
> mingw默认路径是c盘根目录

之前我也考虑过直接使用g++，但是考虑到可能有的人没有安装mingw，并且为了让这个ide一打包放到哪里都能运行，最后使用的是相对路径，附上了精简掉了的g++。
